name: 'Terraform Validation Workflow'
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  terraform_validation:
    name: 'Terraform Validation'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          # provider region is needed when running "terraform validate":
          # https://github.com/hashicorp/terraform/issues/21408
          AWS_DEFAULT_REGION: default